# Generated by Django 4.1.6 on 2023-02-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lexemm', models.CharField(max_length=40, verbose_name='Лексемма')),
                ('morph', models.CharField(blank=True, max_length=60, null=True, verbose_name='Морф разбор')),
                ('role', models.CharField(blank=True, max_length=30, null=True, verbose_name='Роль в предложении')),
            ],
        ),
    ]
