# Generated by Django 4.1.6 on 2023-03-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_textmodel_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextModel',
        ),
    ]
